### PR TITLE
deps: upgrades libuv to 1.18.0

### PR DESCRIPTION
**Pull request by deiga**
This has a possbility of fixing https://github.com/atom/fuzzy-finder/issues/324
in respect to electron having a hard time handling OneDrive filepaths

But I'm not entirely sure if this is the correct way to address this or if this should have been apporached in some other way

### CODE REVIEW

**Comment by deiga** [comment]
`make` fails to seemingly unrelated issues
```
../src/node.cc:255:14: error: no member named 'TraceEventHelper' in namespace 'node::tracing'
    tracing::TraceEventHelper::SetCurrentPlatform(platform_);

../src/node_buffer.cc:63:30: error: no member named 'GetArrayBufferAllocator' in 'v8::Isolate'
  auto* allocator = isolate->GetArrayBufferAllocator();
                    ~~~~~~~  ^
../src/node_buffer.cc:261:16: error: no member named 'GetArrayBufferAllocator' in 'v8::Isolate'
      isolate->GetArrayBufferAllocator()->Free(data, length);
      ~~~~~~~  ^
../src/node_buffer.cc:274:12: error: no member named 'GetArrayBufferAllocator' in 'v8::Isolate'
  isolate->GetArrayBufferAllocator()->Free(data, length);
  ~~~~~~~  ^
../src/node_buffer.cc:317:19: error: no member named 'GetArrayBufferAllocator' in 'v8::Isolate'
  env->isolate()->GetArrayBufferAllocator()->Free(data, length);
  ~~~~~~~~~~~~~~  ^
../src/node_buffer.cc:340:37: error: no member named 'GetArrayBufferAllocator' in 'v8::Isolate'
  auto* allocator = env->isolate()->GetArrayBufferAllocator();
                    ~~~~~~~~~~~~~~  ^
```

**Comment by cjihrig** [comment]
Those errors are unrelated to updating libuv. I just pulled down this repo locally with no changes and got the same errors when trying to build. Someone more familiar with Electron will need to weigh in here.

Side note: if you're going to update libuv, I'd aim for a more recent version. They are all backwards compatible.

**Comment by deiga** [comment]
@cjihrig oh, I didn't even think to check if there is a more recent version. Good point.

**Comment by deiga** [comment]
@cjihrig I upgraded the libuv version to latest 1.18.0 now

**Comment by MarshallOfSound** [comment]
We appear to have `1.18.0` in our currently active branch for node `9.3.0` which will be used in the next minor/major release of Electron.

https://github.com/electron/node/tree/electron-node-v9.3.0

If I misunderstood this PR let me know and I'll reopen it 👍

**Pull request closed without merging**
