### PR TITLE
chore: use boringssl key in process.versions instead of openssl

### PR DESCRIPTION
**Pull request by DeerMichel**
In my opinion here is a better place to fix [this issue](https://github.com/electron/electron/issues/18826) as well as [this one](https://github.com/electron/electron/issues/18827). Basically, this replaces the `process.versions` dict key `openssl` with `boringssl`.

I think the code for getting the version is just fine, since `OPENSSL_VERSION_TEXT` resolves to `OpenSSL 1.1.0 (compatible; BoringSSL)`.

cc @codebytere @erickzhao

### CODE REVIEW

**Comment by codebytere** [comment]
if possible i'd like to hook into the `OPENSSL_IS_BORINGSSL` flag to decide when to set this, as it more directly ensures the key gets set in the right conditions

**Comment by DeerMichel** [comment]
And to default back to `openssl` if that flag is not set?

**Comment by DeerMichel** [comment]
Wait a sec, doesnt compile for some reason

**Comment by DeerMichel** [comment]
Apparently, the `OPENSSL_IS_BORINGSSL` flag is set for the .cc but not for the .h file. A workaround would be to declare both keys in the .h file and only set the appropriate, since the unset one doesnt appear in `process.versions`. Seems odd though...

image

**Comment by nornagon** [comment]
Will this break any modules that expect `process.versions.openssl` to be non-null?

**Comment by DeerMichel** [comment]
Hmm how to find out? We could also fix [this issue](https://github.com/electron/electron/issues/18826) within electron, although it's a bit hacky since that approach would only replace the dict key.

**Comment by ckerr** [comment]
> Apparently, the `OPENSSL_IS_BORINGSSL` flag is set for the .cc but not for the .h file.

If we move this block from node_metadata.cc to node_metadata.h, we can check for `OPENSSL_IS_BORINGSSL` in the header as well.

```cc
#if HAVE_OPENSSL
#include <openssl/opensslv.h>
#endif  // HAVE_OPENSSL
```
e.g. something like this in the header (pseudocode not tested):

```cc
#if HAVE_OPENSSL
#include <openssl/base.h>
#if defined(OPENSSL_IS_BORINGSSL)
#define NODE_VERSIONS_KEY_CRYPTO(V) V(boringssl)
#else
#define NODE_VERSIONS_KEY_CRYPTO(V) V(openssl)
#endif // if defined(OPENSSL_IS_BORINGSSL)
#endif // HAVE_OPENSSL
```

**Comment by DeerMichel** [comment]
Let me check that

**Comment by MarshallOfSound** [comment]
@nornagon I did a cursory search through GitHub code search for `process.versions.openssl` and found not that much --> https://github.com/search?l=Javascript&p=6&q=process.versions.openssl&type=Code

Most of the things I found were TLS tests being skipped if `openssl` was falsey

**Comment by DeerMichel** [comment]
> If we move this block from node_metadata.cc to node_metadata.h, we can check for `OPENSSL_IS_BORINGSSL` in the header as well.

Unfortunately, then it doesnt compile:

image

**Comment by DeerMichel** [comment]
Shelved. See https://github.com/electron/electron/issues/18826#issuecomment-504534264

**Pull request closed without merging**
